services:

  liquidsoap:
    image: savonet/liquidsoap:v2.2.5
    command: ["/script.liq"]
    ports:
    - 8000:8000
    volumes:
    - hls:/tmp
    - ./script.liq:/script.liq:ro

  nginx:
    image: nginx
    ports:
    - 8080:80
    volumes:
    - hls:/mnt:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  hls: {}
